version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
    commands:
      - curl -fsSL https://raw.githubusercontent.com/usdot-jpo-codehub/aws-codebuild-extras/master/install >> extras.sh
      - . ./extras.sh
      # Unit Tests
      - pip install -r requirements.txt
      - coverage run -m pytest
      - coverage xml -i
      # Sonar Scan
      - export SONAR_SCANNER_VERSION=4.0.0.1744
      - export SONAR_SCANNER_HOME=$HOME/.sonar/sonar-scanner-$SONAR_SCANNER_VERSION-linux
      - rm -rf $SONAR_SCANNER_HOME
      - mkdir -p $SONAR_SCANNER_HOME
      - curl -sSLo $HOME/.sonar/sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-$SONAR_SCANNER_VERSION-linux.zip
      - unzip $HOME/.sonar/sonar-scanner.zip -d $HOME/.sonar/
      - rm $HOME/.sonar/sonar-scanner.zip
      - export PATH=$SONAR_SCANNER_HOME/bin:$PATH
      - export SONAR_SCANNER_OPTS="-server"
      - sonar-scanner -Dsonar.projectKey=usdot-its-jpo-data-portal_datahub-ingest -Dsonar.organization=usdot-its-jpo-data-portal -Dsonar.sources=. -Dsonar.exclusions=test_*.py -Dsonar.language=py -Dsonar.host.url=https://sonarcloud.io -Dsonar.python.coverage.reportPaths=coverage.xml -Dsonar.login=$SONAR_TOKEN -Dsonar.branch.name=$CODEBUILD_GIT_BRANCH